// Ported verbatim from the Yoink Home Directions design logic.

const TINT = {
  pink:   ['#FFD6EA', '#FFB9DC'],
  purple: ['#E9DEFF', '#D6C2FF'],
  yellow: ['#FFEDA6', '#FFE177'],
  teal:   ['#C7F5EC', '#A6EEDD'],
  coral:  ['#FFD9C9', '#FFC1A6'],
  blue:   ['#CFE4FF', '#AFD2FF'],
};

const SAT = {
  pink: '#FF3D9A', purple: '#8B5CF6', yellow: '#EFA100',
  teal: '#10B5A0', coral: '#FF6B3D', blue: '#3B82F6',
};

export function stripe(a, b) {
  return `repeating-linear-gradient(135deg,${a} 0 11px,${b} 11px 22px)`;
}

const mk = (o) => ({
  ...o,
  stripe: stripe(TINT[o.hue][0], TINT[o.hue][1]),
  tagColor: SAT[o.hue],
});

export const bazaarItems = [
  mk({ id: 1, name: 'Holographic Frog Sticker Pack', img: 'holo stickers', tag: 'DEAL',  hue: 'pink',   price: '120',   was: '200',   rate: '4.9', sold: '2.1k', almost: true,  left: 16 }),
  mk({ id: 2, name: 'Y2K Bedazzled Flip Phone',       img: 'flip phone',   tag: 'RARE',  hue: 'purple', price: '4,800', was: '6,000', rate: '4.8', sold: '312',  almost: false, left: 0 }),
  mk({ id: 3, name: 'Rubber Duck Army · 50 pc',       img: 'duck army',    tag: 'HOT',   hue: 'yellow', price: '340',   was: '500',   rate: '4.7', sold: '5.4k', almost: false, left: 0 }),
  mk({ id: 4, name: 'Vintage Polaroid Camera',        img: 'polaroid',     tag: 'RETRO', hue: 'teal',   price: '2,200', was: '2,800', rate: '4.9', sold: '880',  almost: true,  left: 38 }),
  mk({ id: 5, name: 'Bubble Lava Lamp',               img: 'lava lamp',    tag: 'TREND', hue: 'coral',  price: '760',   was: '1,100', rate: '4.6', sold: '1.3k', almost: false, left: 0 }),
  mk({ id: 6, name: 'Squishy Mochi Plush',            img: 'mochi plush',  tag: 'CUTE',  hue: 'blue',   price: '290',   was: '420',   rate: '5.0', sold: '9.8k', almost: true,  left: 8 }),
];

export const chips = ['Y2K', 'Retro', 'Oddities', 'Plushies', 'Stickers', 'Tech'];

export const marketCats = ['Pocket Tech', 'Holo Finds', 'Desk Pets', 'Snack Relics', 'Rare Drops'];

export const MARKET_PAGE_SIZE = 8;

const YOINK_DROP_CATALOG = [
  {
    id: 'drop-pocket-tech-bubble-crt',
    name: 'Bubble CRT',
    family: 'Pocket Tech',
    rarity: 'Rare',
    editionSize: 40,
    stockLeft: 7,
    price: 420,
    img: 'bubble crt',
    imageUrl: '/yoink-items/pocket-tech-bubble-crt.png',
    hue: 'purple',
    mode: 'bin',
    seller: 'yoink_lab',
    traits: ['rounded CRT shell', 'grape screen glow', 'sticker antenna', 'foil trim'],
    description: 'A grape-purple desk CRT toy with a tiny pixel face and rare foil trim around the glassy screen.',
  },
  {
    id: 'drop-pocket-tech-jelly-flip-phone',
    name: 'Jelly Flip Phone',
    family: 'Pocket Tech',
    rarity: 'Uncommon',
    editionSize: 90,
    stockLeft: 22,
    price: 260,
    img: 'jelly flip phone',
    imageUrl: '/yoink-items/pocket-tech-jelly-flip-phone.png',
    hue: 'teal',
    mode: 'bin',
    seller: 'yoink_lab',
    traits: ['translucent shell', 'bubble keypad', 'mini screen smile', 'charm loop'],
    description: 'A translucent gummy flip phone with bubble keys, a tiny smiling screen, and a dangling charm loop.',
  },
  {
    id: 'drop-pocket-tech-pocket-pixel-mp3',
    name: 'Pocket Pixel MP3',
    family: 'Pocket Tech',
    rarity: 'Common',
    editionSize: 160,
    stockLeft: 58,
    price: 140,
    img: 'pocket pixel mp3',
    imageUrl: '/yoink-items/pocket-tech-pocket-pixel-mp3.png',
    hue: 'yellow',
    mode: 'bin',
    seller: 'yoink_lab',
    traits: ['pixel face', 'candy buttons', 'matte toy finish', 'lanyard nub'],
    description: 'A tiny yellow music-player toy with candy buttons and a cheerful pixel screen face.',
  },
  {
    id: 'drop-pocket-tech-flashpop-toy-camera',
    name: 'Flashpop Toy Camera',
    family: 'Pocket Tech',
    rarity: 'Ultra Rare',
    editionSize: 18,
    stockLeft: 3,
    price: 760,
    img: 'flashpop toy camera',
    imageUrl: '/yoink-items/pocket-tech-flashpop-toy-camera.png',
    hue: 'pink',
    mode: 'auction',
    seller: 'yoink_lab',
    traits: ['giant teal lens', 'star flash', 'hologlow strap', 'shimmer rim'],
    description: 'An ultra-rare bubblegum camera with a giant teal lens, star flash, and hologlow strap.',
  },
  {
    id: 'drop-holo-finds-frog-foil-card',
    name: 'Frog Foil Card',
    family: 'Holo Finds',
    rarity: 'Rare',
    editionSize: 55,
    stockLeft: 11,
    price: 390,
    img: 'frog foil card',
    imageUrl: '/yoink-items/holo-finds-frog-foil-card.png',
    hue: 'pink',
    mode: 'bin',
    seller: 'foil_friends',
    traits: ['original frog icon', 'rounded slab', 'rainbow foil frame', 'sparkle flecks'],
    description: 'A shiny slabbed card with an original frog icon, rainbow foil frame, and chunky case corners.',
  },
  {
    id: 'drop-holo-finds-cosmic-sticker-slab',
    name: 'Cosmic Sticker Slab',
    family: 'Holo Finds',
    rarity: 'Ultra Rare',
    editionSize: 22,
    stockLeft: 4,
    price: 820,
    img: 'cosmic sticker slab',
    imageUrl: '/yoink-items/holo-finds-cosmic-sticker-slab.png',
    hue: 'purple',
    mode: 'auction',
    seller: 'foil_friends',
    traits: ['clear display slab', 'puffy star sticker', 'iridescent rim', 'soft glow'],
    description: 'A clear display slab with a floating puffy star sticker and a soft cosmic shimmer.',
  },
  {
    id: 'drop-holo-finds-lucky-pog-stack',
    name: 'Lucky Pog Stack',
    family: 'Holo Finds',
    rarity: 'Uncommon',
    editionSize: 100,
    stockLeft: 31,
    price: 210,
    img: 'lucky pog stack',
    imageUrl: '/yoink-items/holo-finds-lucky-pog-stack.png',
    hue: 'coral',
    mode: 'offer',
    seller: 'foil_friends',
    traits: ['stacked tokens', 'foil top cap', 'lucky marks', 'rubbery edges'],
    description: 'A stacked token collectible with rubbery pastel edges and a shiny lucky top cap.',
  },
  {
    id: 'drop-holo-finds-glimmer-ticket-relic',
    name: 'Glimmer Ticket Relic',
    family: 'Holo Finds',
    rarity: 'One-Off',
    editionSize: 1,
    stockLeft: 1,
    price: 1800,
    img: 'glimmer ticket relic',
    imageUrl: '/yoink-items/holo-finds-glimmer-ticket-relic.png',
    hue: 'yellow',
    mode: 'bin',
    seller: 'foil_friends',
    traits: ['oversized ticket shape', 'foil tear edge', 'serial stamp shape', 'teal edge'],
    description: 'A one-off oversized ticket relic with warm shimmer, teal edging, and a tiny serial stamp shape.',
  },
  {
    id: 'drop-desk-pets-mochi-blob',
    name: 'Mochi Blob',
    family: 'Desk Pets',
    rarity: 'Common',
    editionSize: 200,
    stockLeft: 83,
    price: 120,
    img: 'mochi blob',
    imageUrl: '/yoink-items/desk-pets-mochi-blob.png',
    hue: 'pink',
    mode: 'bin',
    seller: 'desk_pet_co',
    traits: ['squishy body', 'dot eyes', 'stubby feet', 'soft blush'],
    description: 'A soft pink desk pet with tiny feet, dot eyes, and a clean matte toy finish.',
  },
  {
    id: 'drop-desk-pets-sleepy-star-charm',
    name: 'Sleepy Star Charm',
    family: 'Desk Pets',
    rarity: 'Rare',
    editionSize: 44,
    stockLeft: 9,
    price: 360,
    img: 'sleepy star charm',
    imageUrl: '/yoink-items/desk-pets-sleepy-star-charm.png',
    hue: 'purple',
    mode: 'bin',
    seller: 'desk_pet_co',
    traits: ['puffy star body', 'sleepy face', 'keychain loop', 'foil cheek patch'],
    description: 'A lavender puffy star charm with sleepy eyes, a tiny loop, and rare foil cheek patches.',
  },
  {
    id: 'drop-desk-pets-button-eye-sprout',
    name: 'Button-Eye Sprout',
    family: 'Desk Pets',
    rarity: 'Uncommon',
    editionSize: 88,
    stockLeft: 26,
    price: 240,
    img: 'button-eye sprout',
    imageUrl: '/yoink-items/desk-pets-button-eye-sprout.png',
    hue: 'teal',
    mode: 'offer',
    seller: 'desk_pet_co',
    traits: ['button eyes', 'leaf hat', 'stitched base', 'coral cheeks'],
    description: 'A sprout mascot with button eyes, a leafy hat, and a stitched vinyl base.',
  },
  {
    id: 'drop-desk-pets-tiny-desk-dino',
    name: 'Tiny Desk Dino',
    family: 'Desk Pets',
    rarity: 'Ultra Rare',
    editionSize: 16,
    stockLeft: 2,
    price: 900,
    img: 'tiny desk dino',
    imageUrl: '/yoink-items/desk-pets-tiny-desk-dino.png',
    hue: 'blue',
    mode: 'auction',
    seller: 'desk_pet_co',
    traits: ['keyboard saddle', 'glow belly', 'serial tag shape', 'purple spine bumps'],
    description: 'An ultra-rare teal desk dinosaur with a keyboard-key saddle and a soft glowing belly.',
  },
  {
    id: 'drop-snack-relics-cereal-prize-rocket',
    name: 'Cereal Prize Rocket',
    family: 'Snack Relics',
    rarity: 'Rare',
    editionSize: 50,
    stockLeft: 12,
    price: 350,
    img: 'cereal prize rocket',
    imageUrl: '/yoink-items/snack-relics-cereal-prize-rocket.png',
    hue: 'coral',
    mode: 'bin',
    seller: 'snack_relics',
    traits: ['rounded fins', 'sticker window', 'foil exhaust puff', 'prize toy finish'],
    description: 'A tiny prize rocket toy with chunky fins, a sticker window, and a foil exhaust puff.',
  },
  {
    id: 'drop-snack-relics-capsule-ghost-toy',
    name: 'Capsule Ghost Toy',
    family: 'Snack Relics',
    rarity: 'Uncommon',
    editionSize: 110,
    stockLeft: 37,
    price: 190,
    img: 'capsule ghost toy',
    imageUrl: '/yoink-items/snack-relics-capsule-ghost-toy.png',
    hue: 'purple',
    mode: 'offer',
    seller: 'snack_relics',
    traits: ['clear capsule', 'friendly ghost', 'pastel latch', 'prize dots'],
    description: 'A vending capsule with a friendly ghost toy tucked inside a glossy pastel shell.',
  },
  {
    id: 'drop-snack-relics-vending-ring-pop-relic',
    name: 'Vending Ring Pop Relic',
    family: 'Snack Relics',
    rarity: 'Ultra Rare',
    editionSize: 20,
    stockLeft: 5,
    price: 700,
    img: 'vending ring pop relic',
    imageUrl: '/yoink-items/snack-relics-vending-ring-pop-relic.png',
    hue: 'teal',
    mode: 'auction',
    seller: 'snack_relics',
    traits: ['toy ring shape', 'faceted gem', 'purple base', 'teal shimmer'],
    description: 'An ultra-rare toy ring relic with a faceted gem, chunky purple base, and teal shimmer.',
  },
  {
    id: 'drop-snack-relics-crinkle-pack-mascot',
    name: 'Crinkle Pack Mascot',
    family: 'Snack Relics',
    rarity: 'One-Off',
    editionSize: 1,
    stockLeft: 1,
    price: 1600,
    img: 'crinkle pack mascot',
    imageUrl: '/yoink-items/snack-relics-crinkle-pack-mascot.png',
    hue: 'yellow',
    mode: 'bin',
    seller: 'snack_relics',
    traits: ['sealed crinkle pack', 'mascot face', 'odd colorway', 'stamp shape'],
    description: 'A one-off sealed crinkle-pack mascot in an odd blackcurrant-lime colorway.',
  },
  // Generated from Desktop/Yoink/yoink-drop-art/item-catalog.json expansion-2026-07-07.
  {
    id: "drop-holo-finds-prism-star-foil-card",
    name: "Prism Star Foil Card",
    family: "Holo Finds",
    rarity: "Ultra Rare",
    editionSize: 12,
    stockLeft: 2,
    price: 1400,
    img: "prism star foil card",
    imageUrl: "/yoink-items/holo-finds-prism-star-foil-card.png",
    hue: "purple",
    mode: 'bin',
    seller: "foil_friends",
    traits: ["slabbed foil card","prism star icon","rainbow chrome edge","serial-stamp shape"],
    description: "Prism Star Foil Card is a slabbed shiny collectible with slabbed foil card, prism star icon, rainbow chrome edge, serial-stamp shape.",
  },
  {
    id: "drop-holo-finds-chrome-heart-foil-card",
    name: "Chrome Heart Foil Card",
    family: "Holo Finds",
    rarity: "Ultra Rare",
    editionSize: 10,
    stockLeft: 2,
    price: 1500,
    img: "chrome heart foil card",
    imageUrl: "/yoink-items/holo-finds-chrome-heart-foil-card.png",
    hue: "pink",
    mode: 'bin',
    seller: "foil_friends",
    traits: ["slabbed foil card","chrome heart icon","pink case corners","rainbow shimmer"],
    description: "Chrome Heart Foil Card is a slabbed shiny collectible with slabbed foil card, chrome heart icon, pink case corners, rainbow shimmer.",
  },
  {
    id: "drop-holo-finds-pixel-crown-foil-card",
    name: "Pixel Crown Foil Card",
    family: "Holo Finds",
    rarity: "Ultra Rare",
    editionSize: 9,
    stockLeft: 1,
    price: 1600,
    img: "pixel crown foil card",
    imageUrl: "/yoink-items/holo-finds-pixel-crown-foil-card.png",
    hue: "yellow",
    mode: 'bin',
    seller: "foil_friends",
    traits: ["slabbed foil card","pixel crown icon","cyan case corners","foil confetti"],
    description: "Pixel Crown Foil Card is a slabbed shiny collectible with slabbed foil card, pixel crown icon, cyan case corners, foil confetti.",
  },
  {
    id: "drop-holo-finds-moon-jelly-foil-card",
    name: "Moon Jelly Foil Card",
    family: "Holo Finds",
    rarity: "Ultra Rare",
    editionSize: 11,
    stockLeft: 2,
    price: 1450,
    img: "moon jelly foil card",
    imageUrl: "/yoink-items/holo-finds-moon-jelly-foil-card.png",
    hue: "purple",
    mode: 'bin',
    seller: "foil_friends",
    traits: ["slabbed foil card","crescent moon bubble","lavender glow","jelly shimmer"],
    description: "Moon Jelly Foil Card is a slabbed shiny collectible with slabbed foil card, crescent moon bubble, lavender glow, jelly shimmer.",
  },
  {
    id: "drop-pocket-tech-mint-bubble-crt",
    name: "Mint Bubble CRT",
    family: "Pocket Tech",
    rarity: "Rare",
    editionSize: 48,
    stockLeft: 11,
    price: 460,
    img: "mint bubble crt",
    imageUrl: "/yoink-items/pocket-tech-mint-bubble-crt.png",
    hue: "teal",
    mode: 'bin',
    seller: "yoink_lab",
    traits: ["rounded CRT shell","mint cabinet","peach screen glow","sticker buttons"],
    description: "Mint Bubble CRT turns nostalgic tiny tech into a chunky Yoink desk toy with rounded CRT shell, mint cabinet, peach screen glow, sticker buttons.",
  },
  {
    id: "drop-pocket-tech-berry-bubble-crt",
    name: "Berry Bubble CRT",
    family: "Pocket Tech",
    rarity: "Rare",
    editionSize: 36,
    stockLeft: 8,
    price: 520,
    img: "berry bubble crt",
    imageUrl: "/yoink-items/pocket-tech-berry-bubble-crt.png",
    hue: "pink",
    mode: 'bin',
    seller: "yoink_lab",
    traits: ["rounded CRT shell","berry cabinet","aqua screen glow","star sticker"],
    description: "Berry Bubble CRT turns nostalgic tiny tech into a chunky Yoink desk toy with rounded CRT shell, berry cabinet, aqua screen glow, star sticker.",
  },
  {
    id: "drop-pocket-tech-lime-jelly-flip",
    name: "Lime Jelly Flip",
    family: "Pocket Tech",
    rarity: "Uncommon",
    editionSize: 84,
    stockLeft: 26,
    price: 360,
    img: "lime jelly flip",
    imageUrl: "/yoink-items/pocket-tech-lime-jelly-flip.png",
    hue: "yellow",
    mode: 'bin',
    seller: "yoink_lab",
    traits: ["translucent flip shell","lime keypad","star charm","tiny screen face"],
    description: "Lime Jelly Flip turns nostalgic tiny tech into a chunky Yoink desk toy with translucent flip shell, lime keypad, star charm, tiny screen face.",
  },
  {
    id: "drop-pocket-tech-coral-jelly-flip",
    name: "Coral Jelly Flip",
    family: "Pocket Tech",
    rarity: "Rare",
    editionSize: 52,
    stockLeft: 11,
    price: 480,
    img: "coral jelly flip",
    imageUrl: "/yoink-items/pocket-tech-coral-jelly-flip.png",
    hue: "coral",
    mode: 'bin',
    seller: "yoink_lab",
    traits: ["translucent coral shell","lavender keypad","moon charm","glossy hinge"],
    description: "Coral Jelly Flip turns nostalgic tiny tech into a chunky Yoink desk toy with translucent coral shell, lavender keypad, moon charm, glossy hinge.",
  },
  {
    id: "drop-pocket-tech-sky-pocket-pixel-mp3",
    name: "Sky Pocket Pixel MP3",
    family: "Pocket Tech",
    rarity: "Common",
    editionSize: 150,
    stockLeft: 63,
    price: 210,
    img: "sky pocket pixel mp3",
    imageUrl: "/yoink-items/pocket-tech-sky-pocket-pixel-mp3.png",
    hue: "teal",
    mode: 'bin',
    seller: "yoink_lab",
    traits: ["sky blue case","pixel screen","round play pad","soft buttons"],
    description: "Sky Pocket Pixel MP3 turns nostalgic tiny tech into a chunky Yoink desk toy with sky blue case, pixel screen, round play pad, soft buttons.",
  },
  {
    id: "drop-pocket-tech-grape-pocket-pixel-mp3",
    name: "Grape Pocket Pixel MP3",
    family: "Pocket Tech",
    rarity: "Uncommon",
    editionSize: 95,
    stockLeft: 29,
    price: 330,
    img: "grape pocket pixel mp3",
    imageUrl: "/yoink-items/pocket-tech-grape-pocket-pixel-mp3.png",
    hue: "purple",
    mode: 'bin',
    seller: "yoink_lab",
    traits: ["grape case","mint screen","orange play pad","side sticker"],
    description: "Grape Pocket Pixel MP3 turns nostalgic tiny tech into a chunky Yoink desk toy with grape case, mint screen, orange play pad, side sticker.",
  },
  {
    id: "drop-pocket-tech-lemon-flashpop-camera",
    name: "Lemon Flashpop Camera",
    family: "Pocket Tech",
    rarity: "Rare",
    editionSize: 42,
    stockLeft: 9,
    price: 540,
    img: "lemon flashpop camera",
    imageUrl: "/yoink-items/pocket-tech-lemon-flashpop-camera.png",
    hue: "yellow",
    mode: 'bin',
    seller: "yoink_lab",
    traits: ["lemon camera body","teal lens","star flash","wrist charm"],
    description: "Lemon Flashpop Camera turns nostalgic tiny tech into a chunky Yoink desk toy with lemon camera body, teal lens, star flash, wrist charm.",
  },
  {
    id: "drop-pocket-tech-teal-flashpop-camera",
    name: "Teal Flashpop Camera",
    family: "Pocket Tech",
    rarity: "Ultra Rare",
    editionSize: 16,
    stockLeft: 3,
    price: 900,
    img: "teal flashpop camera",
    imageUrl: "/yoink-items/pocket-tech-teal-flashpop-camera.png",
    hue: "pink",
    mode: 'bin',
    seller: "yoink_lab",
    traits: ["teal camera body","rainbow lens","pink flash","foil charm"],
    description: "Teal Flashpop Camera turns nostalgic tiny tech into a chunky Yoink desk toy with teal camera body, rainbow lens, pink flash, foil charm.",
  },
  {
    id: "drop-pocket-tech-mini-pager-pal",
    name: "Mini Pager Pal",
    family: "Pocket Tech",
    rarity: "Uncommon",
    editionSize: 80,
    stockLeft: 25,
    price: 340,
    img: "mini pager pal",
    imageUrl: "/yoink-items/pocket-tech-mini-pager-pal.png",
    hue: "teal",
    mode: 'bin',
    seller: "yoink_lab",
    traits: ["rounded pager","mint screen","antenna bead","soft buttons"],
    description: "Mini Pager Pal turns nostalgic tiny tech into a chunky Yoink desk toy with rounded pager, mint screen, antenna bead, soft buttons.",
  },
  {
    id: "drop-pocket-tech-candy-usb-buddy",
    name: "Candy USB Buddy",
    family: "Pocket Tech",
    rarity: "Common",
    editionSize: 140,
    stockLeft: 59,
    price: 240,
    img: "candy usb buddy",
    imageUrl: "/yoink-items/pocket-tech-candy-usb-buddy.png",
    hue: "pink",
    mode: 'bin',
    seller: "yoink_lab",
    traits: ["usb toy","candy shell","tiny display","side plug"],
    description: "Candy USB Buddy turns nostalgic tiny tech into a chunky Yoink desk toy with usb toy, candy shell, tiny display, side plug.",
  },
  {
    id: "drop-desk-pets-blueberry-mochi-blob",
    name: "Blueberry Mochi Blob",
    family: "Desk Pets",
    rarity: "Common",
    editionSize: 220,
    stockLeft: 92,
    price: 160,
    img: "blueberry mochi blob",
    imageUrl: "/yoink-items/desk-pets-blueberry-mochi-blob.png",
    hue: "blue",
    mode: 'bin',
    seller: "desk_pet_co",
    traits: ["round mochi body","blueberry vinyl","tiny feet","star sticker"],
    description: "Blueberry Mochi Blob adds mascot energy to the desk-pet shelf with round mochi body, blueberry vinyl, tiny feet, star sticker.",
  },
  {
    id: "drop-desk-pets-citrus-mochi-blob",
    name: "Citrus Mochi Blob",
    family: "Desk Pets",
    rarity: "Common",
    editionSize: 210,
    stockLeft: 88,
    price: 170,
    img: "citrus mochi blob",
    imageUrl: "/yoink-items/desk-pets-citrus-mochi-blob.png",
    hue: "yellow",
    mode: 'bin',
    seller: "desk_pet_co",
    traits: ["round mochi body","citrus vinyl","tiny feet","heart sticker"],
    description: "Citrus Mochi Blob adds mascot energy to the desk-pet shelf with round mochi body, citrus vinyl, tiny feet, heart sticker.",
  },
  {
    id: "drop-desk-pets-mint-sleepy-star",
    name: "Mint Sleepy Star Charm",
    family: "Desk Pets",
    rarity: "Rare",
    editionSize: 44,
    stockLeft: 10,
    price: 420,
    img: "mint sleepy star charm",
    imageUrl: "/yoink-items/desk-pets-mint-sleepy-star.png",
    hue: "teal",
    mode: 'bin',
    seller: "desk_pet_co",
    traits: ["sleepy star body","mint vinyl","dangling charm","foil cheek"],
    description: "Mint Sleepy Star Charm adds mascot energy to the desk-pet shelf with sleepy star body, mint vinyl, dangling charm, foil cheek.",
  },
  {
    id: "drop-desk-pets-coral-sleepy-star",
    name: "Coral Sleepy Star Charm",
    family: "Desk Pets",
    rarity: "Rare",
    editionSize: 38,
    stockLeft: 8,
    price: 460,
    img: "coral sleepy star charm",
    imageUrl: "/yoink-items/desk-pets-coral-sleepy-star.png",
    hue: "coral",
    mode: 'bin',
    seller: "desk_pet_co",
    traits: ["sleepy star body","coral vinyl","dangling charm","yellow accent"],
    description: "Coral Sleepy Star Charm adds mascot energy to the desk-pet shelf with sleepy star body, coral vinyl, dangling charm, yellow accent.",
  },
  {
    id: "drop-desk-pets-purple-button-eye-sprout",
    name: "Purple Button-Eye Sprout",
    family: "Desk Pets",
    rarity: "Uncommon",
    editionSize: 82,
    stockLeft: 25,
    price: 300,
    img: "purple button-eye sprout",
    imageUrl: "/yoink-items/desk-pets-purple-button-eye-sprout.png",
    hue: "teal",
    mode: 'bin',
    seller: "desk_pet_co",
    traits: ["sprout body","purple plush vinyl","button eyes","mint leaves"],
    description: "Purple Button-Eye Sprout adds mascot energy to the desk-pet shelf with sprout body, purple plush vinyl, button eyes, mint leaves.",
  },
  {
    id: "drop-desk-pets-sunrise-button-eye-sprout",
    name: "Sunrise Button-Eye Sprout",
    family: "Desk Pets",
    rarity: "Rare",
    editionSize: 50,
    stockLeft: 11,
    price: 440,
    img: "sunrise button-eye sprout",
    imageUrl: "/yoink-items/desk-pets-sunrise-button-eye-sprout.png",
    hue: "coral",
    mode: 'bin',
    seller: "desk_pet_co",
    traits: ["sprout body","sunrise body","button eyes","green leaves"],
    description: "Sunrise Button-Eye Sprout adds mascot energy to the desk-pet shelf with sprout body, sunrise body, button eyes, green leaves.",
  },
  {
    id: "drop-desk-pets-lilac-tiny-desk-dino",
    name: "Lilac Tiny Desk Dino",
    family: "Desk Pets",
    rarity: "Ultra Rare",
    editionSize: 18,
    stockLeft: 3,
    price: 880,
    img: "lilac tiny desk dino",
    imageUrl: "/yoink-items/desk-pets-lilac-tiny-desk-dino.png",
    hue: "purple",
    mode: 'bin',
    seller: "desk_pet_co",
    traits: ["tiny dino silhouette","lilac body","star back plates","foil charm"],
    description: "Lilac Tiny Desk Dino adds mascot energy to the desk-pet shelf with tiny dino silhouette, lilac body, star back plates, foil charm.",
  },
  {
    id: "drop-desk-pets-melon-tiny-desk-dino",
    name: "Melon Tiny Desk Dino",
    family: "Desk Pets",
    rarity: "Rare",
    editionSize: 36,
    stockLeft: 8,
    price: 520,
    img: "melon tiny desk dino",
    imageUrl: "/yoink-items/desk-pets-melon-tiny-desk-dino.png",
    hue: "teal",
    mode: 'bin',
    seller: "desk_pet_co",
    traits: ["tiny dino silhouette","melon body","purple back plates","heart sticker"],
    description: "Melon Tiny Desk Dino adds mascot energy to the desk-pet shelf with tiny dino silhouette, melon body, purple back plates, heart sticker.",
  },
  {
    id: "drop-desk-pets-cloud-pillow-pal",
    name: "Cloud Pillow Pal",
    family: "Desk Pets",
    rarity: "Uncommon",
    editionSize: 90,
    stockLeft: 28,
    price: 310,
    img: "cloud pillow pal",
    imageUrl: "/yoink-items/desk-pets-cloud-pillow-pal.png",
    hue: "teal",
    mode: 'bin',
    seller: "desk_pet_co",
    traits: ["pillow body","cloud corners","sleepy face","star sticker"],
    description: "Cloud Pillow Pal adds mascot energy to the desk-pet shelf with pillow body, cloud corners, sleepy face, star sticker.",
  },
  {
    id: "drop-desk-pets-pebble-button-charm",
    name: "Pebble Button Charm",
    family: "Desk Pets",
    rarity: "Uncommon",
    editionSize: 88,
    stockLeft: 27,
    price: 320,
    img: "pebble button charm",
    imageUrl: "/yoink-items/desk-pets-pebble-button-charm.png",
    hue: "purple",
    mode: 'bin',
    seller: "desk_pet_co",
    traits: ["pebble body","button shell","tiny feet","round badge"],
    description: "Pebble Button Charm adds mascot energy to the desk-pet shelf with pebble body, button shell, tiny feet, round badge.",
  },
  {
    id: "drop-snack-relics-blue-rocket-prize",
    name: "Blue Rocket Prize",
    family: "Snack Relics",
    rarity: "Rare",
    editionSize: 56,
    stockLeft: 12,
    price: 430,
    img: "blue rocket prize",
    imageUrl: "/yoink-items/snack-relics-blue-rocket-prize.png",
    hue: "blue",
    mode: 'bin',
    seller: "snack_relics",
    traits: ["cereal prize rocket","blue body","orange fins","porthole face"],
    description: "Blue Rocket Prize feels like a capsule-machine prize relic with cereal prize rocket, blue body, orange fins, porthole face.",
  },
  {
    id: "drop-snack-relics-lime-rocket-prize",
    name: "Lime Rocket Prize",
    family: "Snack Relics",
    rarity: "Rare",
    editionSize: 52,
    stockLeft: 11,
    price: 450,
    img: "lime rocket prize",
    imageUrl: "/yoink-items/snack-relics-lime-rocket-prize.png",
    hue: "yellow",
    mode: 'bin',
    seller: "snack_relics",
    traits: ["cereal prize rocket","lime body","pink fins","star stickers"],
    description: "Lime Rocket Prize feels like a capsule-machine prize relic with cereal prize rocket, lime body, pink fins, star stickers.",
  },
  {
    id: "drop-snack-relics-pink-capsule-ghost",
    name: "Pink Capsule Ghost Toy",
    family: "Snack Relics",
    rarity: "Uncommon",
    editionSize: 118,
    stockLeft: 37,
    price: 260,
    img: "pink capsule ghost toy",
    imageUrl: "/yoink-items/snack-relics-pink-capsule-ghost.png",
    hue: "pink",
    mode: 'bin',
    seller: "snack_relics",
    traits: ["capsule dome","pink base","tiny ghost shape","pastel beads"],
    description: "Pink Capsule Ghost Toy feels like a capsule-machine prize relic with capsule dome, pink base, tiny ghost shape, pastel beads.",
  },
  {
    id: "drop-snack-relics-teal-capsule-ghost",
    name: "Teal Capsule Ghost Toy",
    family: "Snack Relics",
    rarity: "Rare",
    editionSize: 64,
    stockLeft: 14,
    price: 420,
    img: "teal capsule ghost toy",
    imageUrl: "/yoink-items/snack-relics-teal-capsule-ghost.png",
    hue: "teal",
    mode: 'bin',
    seller: "snack_relics",
    traits: ["capsule dome","teal base","tiny ghost shape","foil bead"],
    description: "Teal Capsule Ghost Toy feels like a capsule-machine prize relic with capsule dome, teal base, tiny ghost shape, foil bead.",
  },
  {
    id: "drop-snack-relics-grape-vending-ring",
    name: "Grape Vending Ring Relic",
    family: "Snack Relics",
    rarity: "Ultra Rare",
    editionSize: 20,
    stockLeft: 3,
    price: 820,
    img: "grape vending ring relic",
    imageUrl: "/yoink-items/snack-relics-grape-vending-ring.png",
    hue: "purple",
    mode: 'bin',
    seller: "snack_relics",
    traits: ["chunky ring","grape base","aqua gem","dangling charm"],
    description: "Grape Vending Ring Relic feels like a capsule-machine prize relic with chunky ring, grape base, aqua gem, dangling charm.",
  },
  {
    id: "drop-snack-relics-sunset-vending-ring",
    name: "Sunset Vending Ring Relic",
    family: "Snack Relics",
    rarity: "Rare",
    editionSize: 40,
    stockLeft: 9,
    price: 560,
    img: "sunset vending ring relic",
    imageUrl: "/yoink-items/snack-relics-sunset-vending-ring.png",
    hue: "coral",
    mode: 'bin',
    seller: "snack_relics",
    traits: ["chunky ring","sunset base","mint gem","small charm"],
    description: "Sunset Vending Ring Relic feels like a capsule-machine prize relic with chunky ring, sunset base, mint gem, small charm.",
  },
  {
    id: "drop-snack-relics-mint-crinkle-pack",
    name: "Mint Crinkle Pack Mascot",
    family: "Snack Relics",
    rarity: "Rare",
    editionSize: 46,
    stockLeft: 10,
    price: 470,
    img: "mint crinkle pack mascot",
    imageUrl: "/yoink-items/snack-relics-mint-crinkle-pack.png",
    hue: "teal",
    mode: 'bin',
    seller: "snack_relics",
    traits: ["crinkle pack","mint wrapper","face badge","foil corner"],
    description: "Mint Crinkle Pack Mascot feels like a capsule-machine prize relic with crinkle pack, mint wrapper, face badge, foil corner.",
  },
  {
    id: "drop-snack-relics-berry-crinkle-pack",
    name: "Berry Crinkle Pack Mascot",
    family: "Snack Relics",
    rarity: "Rare",
    editionSize: 42,
    stockLeft: 9,
    price: 490,
    img: "berry crinkle pack mascot",
    imageUrl: "/yoink-items/snack-relics-berry-crinkle-pack.png",
    hue: "pink",
    mode: 'bin',
    seller: "snack_relics",
    traits: ["crinkle pack","berry wrapper","face badge","star sticker"],
    description: "Berry Crinkle Pack Mascot feels like a capsule-machine prize relic with crinkle pack, berry wrapper, face badge, star sticker.",
  },
  {
    id: "drop-snack-relics-soda-tab-prize",
    name: "Soda Tab Prize",
    family: "Snack Relics",
    rarity: "Common",
    editionSize: 160,
    stockLeft: 67,
    price: 190,
    img: "soda tab prize",
    imageUrl: "/yoink-items/snack-relics-soda-tab-prize.png",
    hue: "blue",
    mode: 'bin',
    seller: "snack_relics",
    traits: ["rounded tab","toy metal","inner pull","sticker star"],
    description: "Soda Tab Prize feels like a capsule-machine prize relic with rounded tab, toy metal, inner pull, sticker star.",
  },
  {
    id: "drop-snack-relics-bubble-gum-token",
    name: "Bubble Gum Token",
    family: "Snack Relics",
    rarity: "Uncommon",
    editionSize: 100,
    stockLeft: 31,
    price: 280,
    img: "bubble gum token",
    imageUrl: "/yoink-items/snack-relics-bubble-gum-token.png",
    hue: "pink",
    mode: 'bin',
    seller: "snack_relics",
    traits: ["round token","bubble gum colors","face center","edge dots"],
    description: "Bubble Gum Token feels like a capsule-machine prize relic with round token, bubble gum colors, face center, edge dots.",
  },
];

const MARKET_FEED_ORDER = [
  'drop-pocket-tech-pocket-pixel-mp3',
  'drop-pocket-tech-jelly-flip-phone',
  'drop-desk-pets-mochi-blob',
  'drop-desk-pets-button-eye-sprout',
  'drop-snack-relics-capsule-ghost-toy',
  'drop-holo-finds-lucky-pog-stack',
  'drop-pocket-tech-bubble-crt',
  'drop-snack-relics-cereal-prize-rocket',
  'drop-desk-pets-sleepy-star-charm',
  'drop-holo-finds-frog-foil-card',
  'drop-pocket-tech-flashpop-toy-camera',
  'drop-holo-finds-cosmic-sticker-slab',
  'drop-desk-pets-tiny-desk-dino',
  'drop-snack-relics-vending-ring-pop-relic',
  'drop-holo-finds-glimmer-ticket-relic',
  'drop-snack-relics-crinkle-pack-mascot',
  // Generated Yoink art-pack expansion.
  'drop-holo-finds-prism-star-foil-card',
  'drop-holo-finds-chrome-heart-foil-card',
  'drop-holo-finds-pixel-crown-foil-card',
  'drop-holo-finds-moon-jelly-foil-card',
  'drop-pocket-tech-mint-bubble-crt',
  'drop-pocket-tech-berry-bubble-crt',
  'drop-pocket-tech-lime-jelly-flip',
  'drop-pocket-tech-coral-jelly-flip',
  'drop-pocket-tech-sky-pocket-pixel-mp3',
  'drop-pocket-tech-grape-pocket-pixel-mp3',
  'drop-pocket-tech-lemon-flashpop-camera',
  'drop-pocket-tech-teal-flashpop-camera',
  'drop-pocket-tech-mini-pager-pal',
  'drop-pocket-tech-candy-usb-buddy',
  'drop-desk-pets-blueberry-mochi-blob',
  'drop-desk-pets-citrus-mochi-blob',
  'drop-desk-pets-mint-sleepy-star',
  'drop-desk-pets-coral-sleepy-star',
  'drop-desk-pets-purple-button-eye-sprout',
  'drop-desk-pets-sunrise-button-eye-sprout',
  'drop-desk-pets-lilac-tiny-desk-dino',
  'drop-desk-pets-melon-tiny-desk-dino',
  'drop-desk-pets-cloud-pillow-pal',
  'drop-desk-pets-pebble-button-charm',
  'drop-snack-relics-blue-rocket-prize',
  'drop-snack-relics-lime-rocket-prize',
  'drop-snack-relics-pink-capsule-ghost',
  'drop-snack-relics-teal-capsule-ghost',
  'drop-snack-relics-grape-vending-ring',
  'drop-snack-relics-sunset-vending-ring',
  'drop-snack-relics-mint-crinkle-pack',
  'drop-snack-relics-berry-crinkle-pack',
  'drop-snack-relics-soda-tab-prize',
  'drop-snack-relics-bubble-gum-token',
];

const ALL_MARKET_DROP_CATALOG = MARKET_FEED_ORDER
  .map((id) => YOINK_DROP_CATALOG.find((item) => item.id === id))
  .filter(Boolean);

const flashTierFor = (rarity) => {
  if (rarity === 'Rare') return 'rare';
  if (rarity === 'Ultra Rare' || rarity === 'One-Off') return 'ultra';
  return null;
};

const MARKET_FEED_CATALOG = ALL_MARKET_DROP_CATALOG
  .filter((item) => !flashTierFor(item.rarity));

const TIMED_DROP_POOLS = {
  rare: ALL_MARKET_DROP_CATALOG.filter((item) => flashTierFor(item.rarity) === 'rare'),
  ultra: ALL_MARKET_DROP_CATALOG.filter((item) => flashTierFor(item.rarity) === 'ultra'),
};

export const DROP_REVEAL_WINDOWS = Object.freeze({
  rare: Object.freeze({ minMs: 5000, maxMs: 10000 }),
  ultra: Object.freeze({ minMs: 15000, maxMs: 20000 }),
});

export const MARKET_MAX_ITEMS = MARKET_FEED_CATALOG.length;

function decorateDropListing(item, index) {
  const flashTier = flashTierFor(item.rarity);

  return {
    ...item,
    cond: `${item.rarity} Drop`,
    cta: 'Buy',
    isAuction: false,
    isOffer: false,
    isBin: true,
    price: item.price.toLocaleString(),
    shipFree: item.rarity !== 'One-Off',
    paidShip: item.rarity === 'One-Off',
    ship: '+80 ship',
    fb: `${98 + (index % 2)}.${index % 10}%`,
    topRated: item.rarity === 'Rare' || item.rarity === 'Ultra Rare',
    stripe: stripe(TINT[item.hue][0], TINT[item.hue][1]),
    editionLabel: `Edition of ${item.editionSize}`,
    stockLabel: `${item.stockLeft}/${item.editionSize} left`,
    flashTier,
    flashLabel: flashTier === 'rare' ? 'Rare Flash' : flashTier === 'ultra' ? 'Ultra Rare Drop' : null,
    feedIndex: index,
  };
}

export function makeMarketFeed(start, count) {
  const safeStart = Math.max(0, Math.min(Number(start) || 0, MARKET_MAX_ITEMS));
  const safeCount = Math.max(0, Math.min(Number(count) || 0, MARKET_MAX_ITEMS - safeStart));
  return MARKET_FEED_CATALOG
    .slice(safeStart, safeStart + safeCount)
    .map((item, index) => decorateDropListing(item, safeStart + index));
}

export function appendMarketFeed(current, pageSize = MARKET_PAGE_SIZE, maxItems = MARKET_MAX_ITEMS) {
  if (current.length >= maxItems) return current;
  const nextCount = Math.min(pageSize, maxItems - current.length);
  return current.concat(makeMarketFeed(current.length, nextCount));
}

export function randomDropDelay(window, random = Math.random) {
  const minMs = Math.max(0, Number(window?.minMs) || 0);
  const maxMs = Math.max(minMs, Number(window?.maxMs) || minMs);
  const roll = Math.max(0, Math.min(1, Number(random()) || 0));
  return minMs + Math.floor(roll * (maxMs - minMs));
}

export function makeTimedDrop(tier, random = Math.random) {
  const pool = TIMED_DROP_POOLS[tier] ?? [];
  if (pool.length === 0) return null;
  const roll = Math.max(0, Math.min(0.999999, Number(random()) || 0));
  const item = pool[Math.floor(roll * pool.length)];
  const index = ALL_MARKET_DROP_CATALOG.findIndex((candidate) => candidate.id === item.id);
  return decorateDropListing(item, Math.max(0, index));
}

// Listing-mode filter behind the search bar's "All" chip.
export const MARKET_MODES = ['All', 'Buy now'];

const MODE_MATCHERS = {
  'Buy now': (item) => item.isBin,
};

// Category chips map onto the generated catalog by keyword/condition.
const CATEGORY_MATCHERS = {
  'Pocket Tech': (item) => item.family === 'Pocket Tech',
  'Holo Finds': (item) => item.family === 'Holo Finds',
  'Desk Pets': (item) => item.family === 'Desk Pets',
  'Snack Relics': (item) => item.family === 'Snack Relics',
  'Rare Drops': (item) => ['Rare', 'Ultra Rare', 'One-Off'].includes(item.rarity),
};

export function filterMarketFeed(items, { category = 'For you', mode = 'All', query = '' } = {}) {
  const term = String(query ?? '').trim().toLowerCase();
  const byCategory = CATEGORY_MATCHERS[category];
  const byMode = MODE_MATCHERS[mode];

  return items.filter((item) => {
    if (byCategory && !byCategory(item)) return false;
    if (byMode && !byMode(item)) return false;
    const searchable = [
      item.name,
      item.seller,
      item.family,
      item.rarity,
      item.img,
      ...(item.traits ?? []),
    ].join(' ').toLowerCase();
    if (term && !searchable.includes(term)) return false;
    return true;
  });
}

export const MARKET_SORTS = [
  { id: 'best', label: 'Best match' },
  { id: 'price-low', label: 'Price: low first' },
];

const priceOf = (item) => Number(String(item.price).replace(/,/g, '')) || 0;

export function sortMarketFeed(items, sortId = 'best') {
  if (sortId === 'best') return items;
  const sorted = [...items];
  if (sortId === 'price-low') sorted.sort((a, b) => priceOf(a) - priceOf(b));
  return sorted;
}

export const dropItems = [
  mk({ id: 1, name: 'Crystal Boba Keychain',    img: 'boba charm',   hue: 'purple', price: '480',   left: 8,  total: 40 }),
  mk({ id: 2, name: 'Holo Trading Card · Foil', img: 'foil card',    hue: 'pink',   price: '1,250', left: 23, total: 60 }),
  mk({ id: 3, name: 'Pixel Mini Console',       img: 'mini console', hue: 'teal',   price: '2,900', left: 4,  total: 30 }),
  mk({ id: 4, name: 'Galaxy Slime Jar',         img: 'slime jar',    hue: 'blue',   price: '210',   left: 51, total: 120 }),
].map((it) => ({ ...it, leftPct: Math.max(6, Math.round((it.left / it.total) * 100)) }));

export const pocketItems = [
  mk({ id: 1, name: 'Retro Arcade Coin',     img: 'arcade coin',  hue: 'teal',   price: '180' }),
  mk({ id: 2, name: 'Mini Claw Machine',     img: 'claw machine', hue: 'yellow', price: '1,400' }),
  mk({ id: 3, name: 'Kawaii Cat Eraser Set', img: 'eraser set',   hue: 'pink',   price: '95' }),
  mk({ id: 4, name: 'Pixel Heart Pin',       img: 'heart pin',    hue: 'coral',  price: '150' }),
];

export const sets = [
  { id: 1, name: 'Retro Arcade', have: 3, total: 5, reward: '500', accent: '#6A5ACD', thumbs: [{ h: 'teal', o: true }, { h: 'yellow', o: true }, { h: 'pink', o: true }, { h: 'purple', o: false }, { h: 'coral', o: false }] },
  { id: 2, name: 'Kawaii Squad', have: 2, total: 6, reward: '800', accent: '#6A5ACD', thumbs: [{ h: 'pink', o: true }, { h: 'blue', o: true }, { h: 'yellow', o: false }, { h: 'teal', o: false }, { h: 'purple', o: false }, { h: 'coral', o: false }] },
].map((set) => ({
  ...set,
  pct: Math.round((set.have / set.total) * 100),
  thumbs: set.thumbs.map((th) => ({ ...th, stripe: stripe(TINT[th.h][0], TINT[th.h][1]), locked: !th.o })),
}));

// Quest board definitions. Progress is demo data like the rest of the
// catalog; the server layers claim state (per day / per week) on top.
export const questDefs = [
  { id: 'd-watch',  period: 'daily',  title: 'Watch 3 listings',        icon: 'favorite',              have: 2, goal: 3, reward: 40 },
  { id: 'd-cart',   period: 'daily',  title: 'Add an item to your cart', icon: 'shopping_cart',         have: 1, goal: 1, reward: 60 },
  { id: 'd-browse', period: 'daily',  title: 'Browse 5 categories',      icon: 'category',              have: 3, goal: 5, reward: 30 },
  { id: 'w-orders', period: 'weekly', title: 'Yoink 2 orders',           icon: 'package_2',             have: 1, goal: 2, reward: 250 },
  { id: 'w-set',    period: 'weekly', title: 'Finish a collection set',  icon: 'grid_view',             have: 0, goal: 1, reward: 500 },
  { id: 'w-streak', period: 'weekly', title: 'Keep a 7-day streak',      icon: 'local_fire_department', have: 6, goal: 7, reward: 700 },
];

export const streak = [
  { d: 'M', done: true }, { d: 'T', done: true }, { d: 'W', done: true },
  { d: 'T', done: true }, { d: 'F', done: true }, { d: 'S', done: true, today: true },
  { d: 'S', done: false },
].map((day) => ({ ...day, todo: !day.done }));
